services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guindy_manager_laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
      - bootstrap_cache:/var/www/html/bootstrap/cache
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: guindy_manager_pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: guindy_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: guindy_manager_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  node:
    image: node:14
    container_name: guindy_manager_node
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    tty: true

volumes:
  pgdata:
  storage_data:
  bootstrap_cache:
